export const complaintFormConfig = {
  endpoint: '/api/complaint',
  submitLabel: 'Submit Complaint',
  successMessage: 'Complaint registered!',
  successDescription: 'Our compliance team will review and respond within 3 business days.',
  sections: [
    {
      title: 'Personal Information',
      columns: 2,
      fields: [
        {
          name: 'name',
          label: 'Full Name',
          type: 'text',
          required: true,
          placeholder: 'Your full name',
        },
        {
          name: 'cnic',
          label: 'CNIC Number',
          type: 'text',
          required: true,
          placeholder: '42101-1234567-1',
        },
        {
          name: 'cell',
          label: 'Cell Number',
          type: 'tel',
          required: true,
          placeholder: '+92 300 0000000',
        },
        {
          name: 'email',
          label: 'Email Address',
          type: 'email',
          required: true,
          placeholder: 'your.email@example.com',
        },
        {
          name: 'accountType',
          label: 'Account Type',
          type: 'select',
          required: true,
          placeholder: 'Select account type',
          options: ['Individual', 'Joint', 'Corporate'],
        },
        {
          name: 'tradingAccount',
          label: 'Trading Account No.',
          type: 'text',
          required: false,
          placeholder: 'Your trading account number',
        },
        {
          name: 'address',
          label: 'Address',
          type: 'textarea',
          required: false,
          placeholder: 'Your correspondence address',
          rows: 2,
          colSpan: 2,
        },
      ],
    },
    {
      title: 'Complaint Details',
      columns: 2,
      fields: [
        {
          name: 'complaintType',
          label: 'Complaint Type',
          type: 'select',
          required: true,
          placeholder: 'Select complaint type',
          colSpan: 2,
          options: [
            'Liquidation of outstanding open position without intimation',
            'Non-receipt of security deposit',
            'Unauthorized trades / Spoofing',
            'Buying and selling of shares without consent',
            'Pseudo trading',
            'Delay/non-issuance of documents (contract note, bill, ledger)',
            'Non-execution of orders even with sufficient margins',
            'Transaction charges variation',
            'Overcharging of commission',
            'Non-dissemination of revised commission rates',
            'Execution of orders wrongly causing a loss',
            'Delay in communication of outstanding orders and trades',
            'Suspension of trading account without prior notice',
            'Issue of cheating of broker',
            'No response to queries and complaints',
            'Difference in credit balance',
            'Delay in receipt of credit balance',
            'Issue related to opening and closing of account',
            'Any other service issue with the broker',
          ],
        },
        {
          name: 'complaintAgainst',
          label: 'Complaint Against',
          type: 'select',
          required: false,
          placeholder: 'Select person/department',
          options: ['Agent', 'Operations Staff', 'Management', 'Other'],
        },
        {
          name: 'details',
          label: 'Complaint Details',
          type: 'textarea',
          required: true,
          placeholder: 'Describe your complaint in detail...',
          rows: 6,
          colSpan: 2,
        },
      ],
    },
    {
      title: 'Supporting Documents',
      columns: 1,
      fields: [
        {
          name: 'files',
          label: 'Attach Files',
          type: 'file',
          required: false,
          accept: '.pdf,.jpg,.jpeg',
          multiple: true,
          maxFiles: 5,
          hint: 'PDF or JPG only · Max 5 files · 5MB per file',
        },
      ],
    },
  ],
}