export const whistleblowerFormConfig = {
  endpoint: '/api/whistleblower',
  submitLabel: 'Submit Report',
  successMessage: 'Report submitted confidentially.',
  successDescription: 'Your identity is protected. The board will review your submission.',
  sections: [
    {
      title: 'Details of Alleged Person',
      description: 'Provide as much information as you know. All fields are optional.',
      columns: 2,
      fields: [
        {
          name: 'allegedName',
          label: 'Full Name',
          type: 'text',
          required: false,
          placeholder: 'Name of alleged person',
        },
        {
          name: 'allegedDesignation',
          label: 'Designation',
          type: 'text',
          required: false,
          placeholder: 'Their job title or role',
        },
        {
          name: 'allegedEmail',
          label: 'Email Address',
          type: 'email',
          required: false,
          placeholder: 'Their email (if known)',
        },
        {
          name: 'allegedCompany',
          label: 'Company / Department',
          type: 'text',
          required: false,
          placeholder: 'Company or department name',
        },
        {
          name: 'allegedContact',
          label: 'Contact Number',
          type: 'tel',
          required: false,
          placeholder: 'Their contact number (if known)',
        },
      ],
    },
    {
      title: 'Disclosure Information',
      columns: 2,
      fields: [
        {
          name: 'reason',
          label: 'Reason for Report',
          type: 'select',
          required: true,
          placeholder: 'Select reason',
          colSpan: 2,
          options: [
            'Non-compliance with Rules, Regulations, or Code of Ethics',
            'Violation of Code of Conduct in the workplace',
            'Market manipulation',
            'Leakage of confidential data',
            'Criminal offences, fraud, forgery, or criminal activity',
            'Oversight of internal controls',
            'Professional wrongdoing destroying integrity culture',
            'Unhygienic environment endangering health/safety of employees',
            'Violation of human rights',
            'Improper conduct and unethical behavior',
            'Discriminatory behavior',
            'Financial fraud or malpractices causing loss to customers',
            'Insider trading of commodities',
            'Entering fictitious trades of commodity contracts',
            'Mismanagement for personal benefits',
            'Misappropriation or theft of customer funds or assets',
            'Unauthorized use of company funds',
            'Misappropriation or theft of company assets',
            'Conflict of interest or abuse of authority',
            'Money laundering',
            'Falsification of records',
            'Deliberate concealment of malpractice or wrongdoings',
            'Damage to company reputation or financial loss',
            'Any other concern',
          ],
        },
        {
          name: 'source',
          label: 'Source of Information',
          type: 'text',
          required: false,
          placeholder: 'How did you come across this information?',
          colSpan: 2,
        },
        {
          name: 'disclosureStatement',
          label: 'Detailed Statement',
          type: 'textarea',
          required: true,
          placeholder: 'Describe the concern in as much detail as possible...',
          rows: 7,
          colSpan: 2,
        },
      ],
    },
    {
      title: 'Submission Preference',
      columns: 1,
      fields: [
        {
          name: 'anonymous',
          label: 'Submit anonymously (your identity will not be included in the report)',
          type: 'checkbox',
        },
      ],
    },
    // This section only shows when anonymous is FALSE (unchecked)
    {
      title: 'Your Identity',
      description: 'The company assures full confidentiality. Your details will only be shared with regulatory authorities if legally required.',
      columns: 2,
      showWhen: { field: 'anonymous', value: false },
      fields: [
        {
          name: 'wbName',
          label: 'Full Name',
          type: 'text',
          required: false,
          placeholder: 'Your full name',
        },
        {
          name: 'wbDesignation',
          label: 'Designation',
          type: 'text',
          required: false,
          placeholder: 'Your job title',
        },
        {
          name: 'wbCnic',
          label: 'CNIC Number',
          type: 'text',
          required: false,
          placeholder: '42101-1234567-1',
        },
        {
          name: 'wbContact',
          label: 'Contact Number',
          type: 'tel',
          required: false,
          placeholder: '+92 300 0000000',
        },
        {
          name: 'wbEmail',
          label: 'Email Address',
          type: 'email',
          required: false,
          placeholder: 'your.email@example.com',
        },
        {
          name: 'wbAddress',
          label: 'Mailing Address',
          type: 'textarea',
          required: false,
          placeholder: 'Your mailing address',
          rows: 2,
          colSpan: 2,
        },
      ],
    },
  ],
}